/// `GisilaStudio` — the main entry point for mounting the admin interface.
library gisila_studio.studio;

import 'dart:io';

import 'package:gisila_orm/gisila.dart';
import 'package:shelf/shelf.dart';

import 'auth.dart';
import 'handler.dart';
import 'model_admin.dart';

/// Web-based admin interface for gisila models, inspired by Django admin.
///
/// ## Quick start
///
/// ```dart
/// import 'package:gisila_studio/gisila_studio.dart';
/// import 'package:shelf_router/shelf_router.dart';
///
/// final studio = GisilaStudio(db: db, title: 'Blog Admin');
///
/// studio.register<User>(
///   UserTable.metadata,
///   displayName: 'User',
///   listDisplay: ['id', 'first_name', 'email', 'date_joined'],
///   searchFields: ['first_name', 'last_name', 'email'],
///   readonlyFields: ['id', 'date_joined'],
/// );
///
/// studio.register<Post>(
///   PostTable.metadata,
///   listDisplay: ['id', 'title', 'author_id', 'published_at'],
///   searchFields: ['title'],
///   ordering: ['-published_at'],
/// );
///
/// // Mount under /studio on your existing router:
/// router.mount('/studio', studio.handler(prefix: '/studio'));
///
/// // Or serve standalone:
/// await shelf_io.serve(studio.handler(prefix: ''), 'localhost', 8080);
/// ```
class GisilaStudio {
  final Database _db;

  /// Title shown in the sidebar header and browser tab.
  final String title;

  /// Auth configuration. When non-null every request is gated behind a login
  /// form. Credentials are read from [username] / [password], which default to
  /// the `STUDIO_USERNAME` / `STUDIO_PASSWORD` environment variables.
  final StudioAuth? _auth;

  final List<ModelAdmin<dynamic>> _admins = [];

  /// Creates a [GisilaStudio] instance.
  ///
  /// If [username] and [password] are both provided (or found in the
  /// environment variables `STUDIO_USERNAME` and `STUDIO_PASSWORD`), a login
  /// form is required before accessing any page.  If neither env var is set and
  /// no explicit credentials are passed, the studio runs without authentication.
  GisilaStudio({
    required Database db,
    this.title = 'Gisila Studio',
    String? username,
    String? password,
  })  : _db = db,
        _auth = _buildAuth(username, password);

  static StudioAuth? _buildAuth(String? username, String? password) {
    final u = username ?? Platform.environment['STUDIO_USERNAME'];
    final p = password ?? Platform.environment['STUDIO_PASSWORD'];
    if (u != null && u.isNotEmpty && p != null && p.isNotEmpty) {
      return StudioAuth(username: u, password: p);
    }
    return null;
  }

  /// Register a model with the admin.
  ///
  /// [meta] is the `TableMeta<T>` generated by build_runner (e.g.
  /// `UserTable.metadata`).
  ///
  /// Optional parameters mirror Django's `ModelAdmin` class:
  ///
  /// * [displayName] — human-readable singular name, e.g. `"User"`.
  /// * [displayNamePlural] — human-readable plural, e.g. `"Users"`.
  /// * [listDisplay] — which columns appear in the list view (default: first 6).
  /// * [searchFields] — columns to `ILIKE` search against.
  /// * [readonlyFields] — columns shown on forms but not editable.
  /// * [excludeFields] — columns completely hidden from forms.
  /// * [pageSize] — rows per page (default 25).
  /// * [ordering] — default list ordering; prefix with `-` for DESC,
  ///   e.g. `['-date_joined', 'email']`.
  void register<T>(
    TableMeta<T> meta, {
    String? displayName,
    String? displayNamePlural,
    List<String>? listDisplay,
    List<String> searchFields = const [],
    List<String> readonlyFields = const [],
    List<String> excludeFields = const [],
    int pageSize = 25,
    List<String> ordering = const [],
    String? group,
  }) {
    _admins.add(buildModelAdmin<T>(
      meta,
      displayName: displayName,
      displayNamePlural: displayNamePlural,
      listDisplay: listDisplay,
      searchFields: searchFields,
      readonlyFields: readonlyFields,
      excludeFields: excludeFields,
      pageSize: pageSize,
      ordering: ordering,
      group: group,
    ));
  }

  /// Build the Shelf [Handler] for the admin interface.
  ///
  /// [prefix] must match the URL path where the handler is mounted so that
  /// all internal links are generated correctly. For example, if you mount
  /// at `/admin`, pass `prefix: '/admin'`.
  ///
  /// When serving standalone (not mounted under a parent router), pass an
  /// empty string: `prefix: ''`.
  Handler handler({String prefix = '/studio'}) {
    // Normalise: no trailing slash.
    final p =
        prefix.endsWith('/') ? prefix.substring(0, prefix.length - 1) : prefix;

    return buildStudioHandler(
      admins: List.unmodifiable(_admins),
      db: _db,
      prefix: p,
      title: title,
      auth: _auth,
    );
  }
}
